jwt:
  expiration: 60  # 單位秒

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/InterviewWorks
    username: root
    password: 1234

# jdbc:h2:file:C:/A_TestSpring/project_backend/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
# testdb.mv.db

mybatis:
  mapper-locations: classpath:Mapper/*.xml  #注意：一定要對應mapper映射xml文件的所在路徑
  configuration:
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制檯打印sql語句方便調試sql語句執行錯誤
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:這個不在控制檯打印查詢結果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    mapUnderscoreToCamelCase: true # 開啓駝峯命名轉換法

logging:
  config: classpath:log4j2.xml
  level:
    #這個指定你的dao層，也就是mapper文件的所在包
    com.example.demo.Mapper: DEBUG